# Site settings
title: Nicolas Benedit - Architecture and Design
email: nicolas@benedit.com
description: Based in Barcelona since 2001 and born in Buenos Aires, Nicol√°s is an architect and an industrial design enthusiast creating is own line of lamps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Exclude from processing.
exclude:
  - node_modules
  - src
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json
  - README.md

# Include in processing.
include:
  - _pages

# Do not clean when building
keep_files:
  - assets
